{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "0d469f11",
   "metadata": {},
   "source": [
    "## Python_Modul_Week_4\n",
    "\n",
    "Kütüphane Projesi\n",
    "\n",
    "Bu projede, şimdiye kadar öğrendiğiniz Python bilgilerini kullanarak bir kütüphane programı yazmanızı istiyoruz. Hata yakalama, dosya işlemleri – özellikle Json modülü ve dosya bilgileri – kullanılacaktır.\n",
    "\n",
    "Bir kütüphanede; iki ana bölüm vardır: Üyelik işlemleri ve Kitap işlemleri.\n",
    "Üyelik işlemleri; üye ekleme, üye silme, üye kontrolü, üyeye kitap verme ve üyeden kitap geri alma bilgilerini içerir. Üyelik verilerinin kaydedildiği bir veritabanı veya dosya da gereklidir.\n",
    "\n",
    "Kitap işlemleri için de benzer şeyler söylenebilir.\n",
    "\n",
    "Projenin Detaylandırılması:\n",
    "\n",
    "Proje; main.py, Kitap_Transactions.py, Member_Transactions.py, Zaman.py dosyalarından oluşacaktır.\n",
    "\n",
    "main.py:\n",
    "\n",
    "Projemizin ana dosyası main.py dosyası olacaktır. İşlemler bu dosyadan yürütülecek, diğer Python dosyaları buradan modül olarak çağrılacaktır. Örneğin, kitap ekleme, kitap silme, üye ekleme, üyeye kitap verme ve üye kontrolü işlemleri burada yapılacaktır.\n",
    "\n",
    "\n",
    "![Sample Image](resimler/1.png)\n",
    "\n",
    "Aşağıda bu projenin bir çalıştırma çıktısını göreceksiniz.\n",
    "Ana sayfadaki (main.py) girişler (input) aracılığıyla book_transactions ve membership_transactions modüllerindeki fonksiyonları çalıştırabilirsiniz.\n",
    "**Image URL**\n",
    "\n",
    "![Sample Image](resimler/2.png)\n",
    "\n",
    "book_islemleri.py :\n",
    "\n",
    "Bu modülde, kitap bilgilerini (kayıtlı kitaplar ve toplam sayı), ekleme, silme, arama ve güncelleme işlevlerini yazacaksınız.\n",
    "Verilerimizi kitap.json dosyasına kaydedeceğiz. kitap.json dosyası size verilecektir (isterseniz kendiniz de oluşturabilirsiniz).\n",
    "Dosya kontrolü os modülü ile yapılmalıdır.\n",
    "\n",
    "Aşağıda kitap işlemleri için örnek fonksiyonlar bulabilirsiniz; ancak bu fonksiyonları takip etmek zorunda değilsiniz, kendi planlamanızı da yapabilirsiniz.\n",
    "\n",
    "\n",
    "![Sample Image](resimler/3.png)\n",
    "\n",
    "Kitap.json dosyasında çok fazla veri bulunmaktadır. Biz aşağıdaki verilerle çalışacağız. Yeni veri eklerken ya da arama yaparken bu verileri temel alacağız.\n",
    "**Image URL**\n",
    "\n",
    "![Sample Image](resimler/4.png)\n",
    "Book.json :\n",
    "sample output is as follows\n",
    "\n",
    "**Image URL**\n",
    "\n",
    "![Sample Image](resimler/5.png)\n",
    "\n",
    "uye_islemleri.py:\n",
    "Burada; üye bilgileri (üye isimleri ve toplam üye sayısı), üye güncelleme, üye ekleme, üye arama, üye silme, kitap ödünç verme ve kitap iade alma gibi işlemler gerçekleştirilecektir.\n",
    "\n",
    "Ayrıca, üyeler uye.json dosyasına kaydedilmelidir.\n",
    "Bir kitaba ödünç verildiğinde mutlaka:\n",
    "\n",
    "Kitabın ödünç verildiği tarih ve saat,\n",
    "\n",
    "İki hafta sonraki iade tarihi\n",
    "eklenmeli ve bu bilgiler taksi.json dosyasına kaydedilmelidir.\n",
    "\n",
    "\n",
    "![Sample Image](resimler/6.png)\n",
    "\n",
    "Bu işlemleri, modülü (Python dosyasını) kendimiz oluşturduğumuzda gerçekleştireceğiz.\n",
    "Kitap ödünç verildikten sonra, bu bilgi taksi.json dosyasına kaydedilecek.\n",
    "Ardından, ödünç verilen kitap kitap.json dosyasından silinmelidir, böylece başka bir kullanıcı bu kitabı tekrar almaya çalıştığında görünmemelidir.\n",
    "\n",
    "Not: uye.json ve taksi.json dosyalarını siz kendiniz oluşturacaksınız.\n",
    "**Image URL**\n",
    "\n",
    "![Sample Image](resimler/7.png)\n",
    "\n",
    "Uye.json dosyasına kaydedeceğiniz veriler aşağıdaki formatta olmalıdır:\n",
    "**Image URL**\n",
    "\n",
    "![Sample Image](resimler/8.png)\n",
    "\n",
    "time.py :\n",
    "Kitaplarımızı üyelerimize 2 haftalığına ödünç veriyoruz.\n",
    "Bu nedenle, bu modül sayesinde ödünç verme tarihini ve saatini ve kitabın iade edilmesi gereken tarihi kaydedeceğiz.\n",
    "Bu modülü çalıştırdığımızda, bize şu anki tarih ve saati ve 2 hafta sonrasının tarihini döndürmesini istiyoruz.\n",
    "\n",
    "**Image URL**\n",
    "\n",
    "![Sample Image](resimler/9.png)\n",
    "\n",
    "Tracking.json dosyasına kaydedeceğiniz veriler aşağıdaki formatta olmalıdır:\n",
    "\n",
    "**Image URL**\n",
    "\n",
    "![Sample Image](resimler/10.png)\n",
    "\n",
    "Hackerrank Questions\n",
    "Diagonal Difference: https://www.hackerrank.com/challenges/diagonal-difference/problem\n",
    "\n",
    "Left Rotation: https://www.hackerrank.com/challenges/array-left-rotation/problem\n",
    "\n",
    "Counter game: https://www.hackerrank.com/challenges/counter-game/problem\n",
    "\n",
    "Time Delta: https://www.hackerrank.com/challenges/python-time-delta/problem"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "453cf7ca",
   "metadata": {},
   "outputs": [],
   "source": [
    "from IPython.display import clear_output\n",
    "import Mahmut_Engin_Ti_week4\n",
    "import adnan_team4_member_week4_zaman\n",
    "import Emre_team4_member\n",
    "\n",
    "\n",
    "def halk_kutuphanesi_menu():\n",
    "    while True:\n",
    "        print(\"Halk Kütüphanemize Hoşgeldiniz!\")\n",
    "        print(\"1- UYELIK ISLEMLERI\")\n",
    "        print(\"2- KITAP ISLEMLERI\")\n",
    "        print(\"3- CIKIS\")\n",
    "\n",
    "        while True:\n",
    "            try:\n",
    "                secim = input(\"Lutfen yapmak istediginiz secimin kodunu giriniz (1, 2, 3): \")\n",
    "                break\n",
    "            except Exception as hata:\n",
    "                print(\"hata \",hata, end=\"\\n\\n\")\n",
    "                break\n",
    "\n",
    "        if secim == '1':\n",
    "\n",
    "            clear_output(wait=True)\n",
    "\n",
    "            print(\"1- UYELER\") # burayi ben yapicam\n",
    "            print(\"2- UYE EKLEME\")\n",
    "            print(\"3- UYE ARA\")\n",
    "            print(\"4- UYE SIL\")\n",
    "            print(\"5- KITAP ODUNC VERME\")\n",
    "            print(\"6- KITAP IADE\")\n",
    "            print(\"7- KITAP TAKIBI\")\n",
    "            print(\"0- CIKIS\")\n",
    "            birinci_secim = input(\"islem seciniz (0-7):\")\n",
    "\n",
    "            if birinci_secim == '1':\n",
    "                pass\n",
    "            elif birinci_secim == '2':\n",
    "                Mahmut_Engin_Ti_week4.uye_ekle()\n",
    "            elif birinci_secim == '3':\n",
    "                Mahmut_Engin_Ti_week4.uye_ara()\n",
    "            elif birinci_secim == '4':\n",
    "                Mahmut_Engin_Ti_week4.uye_sil()\n",
    "            elif birinci_secim == '5':\n",
    "                Mahmut_Engin_Ti_week4.kitap_odunc_verme()\n",
    "            elif birinci_secim == '6':\n",
    "                Mahmut_Engin_Ti_week4.kitap_iade()\n",
    "            elif birinci_secim == '7':\n",
    "                Mahmut_Engin_Ti_week4.kitap_takibi()\n",
    "            elif birinci_secim == '0':\n",
    "                break\n",
    "            else:\n",
    "                print(\"Geçersiz seçim, lütfen 0-7 arasında bir değer giriniz.\")\n",
    "            \n",
    "        elif secim == '2':\n",
    "            clear_output(wait=True)\n",
    "\n",
    "            print(\"1-KITAPLAR\") #burayi ben yapicam\n",
    "            print(\"2- KITAP EKLEME\")\n",
    "            print(\"3-KITAP ARA\")\n",
    "            print(\"4-KITAP SIL\")\n",
    "            print(\"0-CIKIS\")\n",
    "            ikici_secim = input(\"islem seciniz\")\n",
    "\n",
    "            if ikici_secim == '1':\n",
    "                pass\n",
    "            elif ikici_secim == '2':\n",
    "                Emre_team4_member.kitap_ekleme()\n",
    "            elif ikici_secim == '3':\n",
    "                Emre_team4_member.kitap_kontrolu()\n",
    "            elif ikici_secim == '4':\n",
    "                Emre_team4_member.kitap_silme()\n",
    "            elif ikici_secim == '0':\n",
    "                break\n",
    "            else:\n",
    "                print(\"Geçersiz seçim, lütfen 0-4 arasında bir değer giriniz.\")\n",
    "\n",
    "        elif secim == '3':\n",
    "            print(\"Çıkış yapılıyor... Görüşmek üzere!\")\n",
    "            break  # Programdan çıkış yapar\n",
    "        else:\n",
    "            print(\"Geçersiz seçenek, lütfen tekrar deneyin.\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    halk_kutuphanesi_menu()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
